/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) throws Exception{
        var fxml = getClass().getResource("/org/example/main.fxml");
        var root = javafx.fxml.FXMLLoader.load(fxml);

        var scene = new javafx.scene.Scene((Parent) root,400,500);
        stage.setTitle("Alarm Clock");
        stage.setScene(scene);
        stage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }
}
